# Generated by Django 3.0.1 on 2019-12-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_trekkingguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
