# Generated by Django 3.0.1 on 2019-12-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
