# Generated by Django 3.0.1 on 2020-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_bookdestinations_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
