# Generated by Django 3.0.1 on 2020-01-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200109_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='destination',
        ),
    ]
