# Generated by Django 3.0.1 on 2020-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_remove_booked_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingguide',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
