# Generated by Django 3.0.1 on 2020-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_remove_booked_guide_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingguide',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
