# Generated by Django 3.0.1 on 2020-01-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_trekkingguide_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdestinations',
            options={'verbose_name_plural': 'BookDestination'},
        ),
        migrations.AlterModelOptions(
            name='booked',
            options={'verbose_name_plural': 'Booked'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='trekkingguide',
            options={'verbose_name_plural': 'Trekking guide'},
        ),
    ]
